plugins {
    id 'net.fabricmc.fabric-loom' version '1.15.5'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

loom {
    enableModProvidedJavadoc.set(false)

    runs {
        client {
            client()
            configName = "Fabric Client"
            runDir = "run/client"
        }
        server {
            server()
            configName = "Fabric Server"
            runDir = "run/server"
            vmArg "-Dfabric.log.level=info"
        }
    }
}

processResources {
    def resourceProps = [
            version         : project.version,
            loader_version  : project.loader_version,
            minecraft_version: project.minecraft_version,
            java_version    : project.java_version,
            fabric_version  : project.fabric_version
    ]

    inputs.properties(resourceProps)

    filesMatching('fabric.mod.json') {
        expand(resourceProps)
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = project.java_version as int
}

java {
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(project.java_version as int)
    }
    sourceCompatibility = JavaVersion.toVersion(project.java_version)
    targetCompatibility = JavaVersion.toVersion(project.java_version)
}

tasks.matching { it.name == 'remapJar' || it.name == 'remapSourcesJar' }.configureEach {
    enabled = false
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
